### ISSUE TITLE
Strip down the base image (off the lede-17.01-mc branch)

### ISSUE THREAD

**Issue by darabi** [m-creations/openwrt#1]
In Docker containers, we don't need most of the networking stuff which is in the normal OpenWrt/LEDE rootfs.

Please remove as many packages as possible. Some basic utilities to diagnose network problems should remain there (e.g. ping, ifconfig).

**Comment by exquisitus** [comment]
Comparing the output of the command `opkg list-installed` from inside a running image before and after the change, we see that the following packages have now been removed: 
> ca-certificates
> ip6tables
> iptables
> kernel
> kmod-e1000
> kmod-i2c-algo-bit
> kmod-i2c-core
> kmod-igb
> kmod-input-core
> kmod-input-evdev
> kmod-ip6tables
> kmod-ipt-conntrack
> kmod-ipt-core
> kmod-lib-crc-ccitt
> kmod-nf-conntrack
> kmod-nf-conntrack6
> kmod-nf-ipt
> kmod-nf-ipt6
> kmod-nf-nat
> kmod-ppp
> kmod-pppoe
> kmod-pppox
> kmod-pps
> kmod-ptp
> kmod-slhc
> libf2fs
> libip4tc
> libip6tc
> libncurses
> libxtables
> mkf2fs
> odhcp6c
> odhcpd
> ppp
> ppp-mod-pppoe
> terminfo

The packages which remain are:
> base-files - 173-r3530+1-1687aa4
> busybox - 1.25.1-4
> fstools - 2016-12-04-84b530a7-2
> fwtool - 1
> jshn - 2017-02-24-96305a3c-1
> jsonfilter - 2016-07-02-dea067ad-1
> lede-keyring - 2017-01-20-a50b7529-1
> libblobmsg-json - 2017-02-24-96305a3c-1
> libc - 2.24-1
> libgcc - 5.4.0-1
> libjson-c - 0.12.1-1
> libjson-script - 2017-02-24-96305a3c-1
> libnl-tiny - 0.1-5
> libopenssl - 1.0.2k-1
> libpthread - 2.24-1
> librt - 2.24-1
> libssp - 5.4.0-1
> libubox - 2017-02-24-96305a3c-1
> libubus - 2017-02-18-34c6e818-1
> libuci - 2016-07-04-e1bf4356-1
> libuclient - 2016-12-09-52d955fd-1
> libuuid - 2.29.2-1
> logd - 2017-03-10-16f7e161-1
> netifd - 2017-01-25-650758b1-1
> opkg - 2017-03-23-1d0263bb-1
> procd - 2017-02-15-5f912410-1
> ubox - 2017-03-10-16f7e161-1
> ubus - 2017-02-18-34c6e818-1
> ubusd - 2017-02-18-34c6e818-1
> uci - 2016-07-04-e1bf4356-1
> uclient-fetch - 2016-12-09-52d955fd-1
> usign - 2015-07-04-ef641914-1
> zlib - 1.2.11-1
(33 packages)

**Comment by darabi** [comment]
Great!

I guess it will be difficult to remove much more, if the image should be capable of running procd, ubusd and uci.
Let's make some tests with these packages and see how it goes.

**Comment by darabi** [comment]
Commit 3178228 still contains `curl` and doesn't have the correct download URL, but I close this issue as the main work has been finished.
